Exception on / [POST]
Traceback (most recent call last):
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/m/Dropbox/Projects/OperatorAware/GitPath/operatoraware/app/routes.py", line 34, in indexpost
    authenticated = check_passphrase(pswd_from_user, passphrase_file_path='supervisor_passphrases.keys')
  File "/home/m/Dropbox/Projects/OperatorAware/GitPath/operatoraware/operator_aware_lib/check_passphrase.py", line 11, in check_passphrase
    wordlistFile = open(passphrase_file_path, 'r')  # open wordlist, e.g. BIP39
FileNotFoundError: [Errno 2] No such file or directory: 'supervisor_passphrases.keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1719, in handle_user_exception
    return handler(e)
  File "/home/m/Dropbox/Projects/OperatorAware/GitPath/operatoraware/app/__init__.py", line 40, in exceptions
    tb = traceback.format_exc()
NameError: name 'traceback' is not defined
[2018-Jun-28 14:06] 127.0.0.1 GET http /? 200 OK
Exception on / [POST]
Traceback (most recent call last):
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/m/Dropbox/Projects/OperatorAware/GitPath/operatoraware/app/routes.py", line 34, in indexpost
    authenticated = check_passphrase(pswd_from_user, passphrase_file_path='supervisor_passphrases.keys')
  File "/home/m/Dropbox/Projects/OperatorAware/GitPath/operatoraware/operator_aware_lib/check_passphrase.py", line 11, in check_passphrase
    wordlistFile = open(passphrase_file_path, 'r')  # open wordlist, e.g. BIP39
FileNotFoundError: [Errno 2] No such file or directory: 'supervisor_passphrases.keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1719, in handle_user_exception
    return handler(e)
  File "/home/m/Dropbox/Projects/OperatorAware/GitPath/operatoraware/app/__init__.py", line 40, in exceptions
    tb = traceback.format_exc()
NameError: name 'traceback' is not defined
[2018-Jun-28 14:07] 127.0.0.1 GET http /? 200 OK
Exception on / [POST]
Traceback (most recent call last):
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/m/Dropbox/Projects/OperatorAware/GitPath/operatoraware/app/routes.py", line 34, in indexpost
    authenticated = check_passphrase(pswd_from_user, passphrase_file_path='supervisor_passphrases.keys')
  File "/home/m/Dropbox/Projects/OperatorAware/GitPath/operatoraware/operator_aware_lib/check_passphrase.py", line 11, in check_passphrase
    wordlistFile = open(passphrase_file_path, 'r')  # open wordlist, e.g. BIP39
FileNotFoundError: [Errno 2] No such file or directory: 'supervisor_passphrases.keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1719, in handle_user_exception
    return handler(e)
  File "/home/m/Dropbox/Projects/OperatorAware/GitPath/operatoraware/app/__init__.py", line 40, in exceptions
    tb = traceback.format_exc()
NameError: name 'traceback' is not defined
[2018-Jun-28 14:08] 127.0.0.1 GET http /? 200 OK
Exception on / [POST]
Traceback (most recent call last):
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/m/Dropbox/Projects/OperatorAware/GitPath/operatoraware/app/routes.py", line 34, in indexpost
    authenticated = check_passphrase(pswd_from_user, passphrase_file_path='supervisor_passphrases.keys')
  File "/home/m/Dropbox/Projects/OperatorAware/GitPath/operatoraware/operator_aware_lib/check_passphrase.py", line 11, in check_passphrase
    wordlistFile = open(passphrase_file_path, 'r')  # open wordlist, e.g. BIP39
FileNotFoundError: [Errno 2] No such file or directory: 'supervisor_passphrases.keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1719, in handle_user_exception
    return handler(e)
  File "/home/m/Dropbox/Projects/OperatorAware/GitPath/operatoraware/app/__init__.py", line 40, in exceptions
    tb = traceback.format_exc()
NameError: name 'traceback' is not defined
[2018-Jun-28 14:09] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:11] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:13] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:14] 127.0.0.1 POST http /? 200 OK
[2018-Jun-28 14:14] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:14] 127.0.0.1 POST http /? 200 OK
[2018-Jun-28 14:15] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:15] 127.0.0.1 POST http /? 200 OK
[2018-Jun-28 14:15] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:15] 127.0.0.1 POST http /? 200 OK
[2018-Jun-28 14:17] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:17] 127.0.0.1 POST http /? 200 OK
[2018-Jun-28 14:18] 127.0.0.1 POST http /? 200 OK
[2018-Jun-28 14:18] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:18] 127.0.0.1 GET http /static/css/normalize.css? 200 OK
[2018-Jun-28 14:18] 127.0.0.1 GET http /static/css/demo.css? 304 NOT MODIFIED
[2018-Jun-28 14:18] 127.0.0.1 GET http /static/css/component.css? 304 NOT MODIFIED
[2018-Jun-28 14:19] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:19] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:21] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:21] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:22] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:22] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:22] 127.0.0.1 GET http /static/css/normalize.css? 304 NOT MODIFIED
[2018-Jun-28 14:22] 127.0.0.1 GET http /static/css/demo.css? 304 NOT MODIFIED
[2018-Jun-28 14:22] 127.0.0.1 GET http /static/css/component.css? 304 NOT MODIFIED
[2018-Jun-28 14:22] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:22] 127.0.0.1 GET http /static/css/normalize.css? 304 NOT MODIFIED
[2018-Jun-28 14:22] 127.0.0.1 GET http /static/css/demo.css? 304 NOT MODIFIED
[2018-Jun-28 14:22] 127.0.0.1 GET http /static/css/component.css? 304 NOT MODIFIED
[2018-Jun-28 14:23] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:23] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:23] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:23] 127.0.0.1 GET http /static/css/normalize.css? 304 NOT MODIFIED
[2018-Jun-28 14:23] 127.0.0.1 GET http /static/css/demo.css? 304 NOT MODIFIED
[2018-Jun-28 14:23] 127.0.0.1 GET http /static/css/component.css? 304 NOT MODIFIED
[2018-Jun-28 14:24] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:24] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:24] 127.0.0.1 GET http /static/css/normalize.css? 304 NOT MODIFIED
[2018-Jun-28 14:24] 127.0.0.1 GET http /static/css/demo.css? 304 NOT MODIFIED
[2018-Jun-28 14:24] 127.0.0.1 GET http /static/css/component.css? 304 NOT MODIFIED
[2018-Jun-28 14:24] 127.0.0.1 POST http /? 200 OK
[2018-Jun-28 14:25] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:25] 127.0.0.1 GET http /static/css/normalize.css? 304 NOT MODIFIED
[2018-Jun-28 14:25] 127.0.0.1 GET http /static/css/component.css? 304 NOT MODIFIED
[2018-Jun-28 14:25] 127.0.0.1 GET http /static/css/demo.css? 304 NOT MODIFIED
[2018-Jun-28 14:25] 127.0.0.1 POST http /? 200 OK
[2018-Jun-28 14:26] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:26] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:26] 127.0.0.1 GET http /static/css/demo.css? 304 NOT MODIFIED
[2018-Jun-28 14:26] 127.0.0.1 GET http /static/css/normalize.css? 304 NOT MODIFIED
[2018-Jun-28 14:26] 127.0.0.1 GET http /static/css/component.css? 304 NOT MODIFIED
[2018-Jun-28 14:30] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:30] 127.0.0.1 POST http /? 200 OK
[2018-Jun-28 14:35] 127.0.0.1 GET http /? 200 OK
[2018-Jun-28 14:35] 127.0.0.1 GET http /static/css/normalize.css? 304 NOT MODIFIED
[2018-Jun-28 14:35] 127.0.0.1 GET http /static/css/component.css? 304 NOT MODIFIED
